export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SERVER_REPONSE_ERROR = 'LOGIN_USER_SERVER_REPONSE_ERROR';
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS = 'LOGIN_USER_SERVER_RESPONSE_SUCCESS';

export const SERVER_CALL_FAILED = 'SERVER_CALL_FAILED';

export const LOGOUT_USER  = 'LOGOUT_USER';
export const LOGOUT_USER_SERVER_RESPONSE_SUCCESS = 'LOGOUT_USER_SERVER_RESPONSE_SUCCESS';
export const SERVER_REPONSE_ERROR = 'SERVER_REPONSE_ERROR';
export const LOGOUT_USER_SERVER_REPONSE_ERROR = 'LOGOUT_USER_SERVER_REPONSE_ERROR';

export const VALIDATE_TOKEN = "VALIDATE_TOKEN";
export const VALIDATE_TOKEN_SERVER_RESPONSE_SUCCESS = "VALIDATE_TOKEN_SERVER_RESPONSE_SUCCESS";
export const VALIDATE_TOKEN_SERVER_REPONSE_ERROR = "VALIDATE_TOKEN_SERVER_REPONSE_ERROR";
export const VALIDATE_TOKEN_SERVER_CALL_FAILED = "VALIDATE_TOKEN_SERVER_CALL_FAILED";
export const IS_USER_LOGGED_IN = 'IS_USER_LOGGED_IN';


 export const GET_VISA_TYPE_LIST = 'GET_VISA_TYPE_LIST';// H1b , GC, EAD,
 export const GET_EMPLOYEE_ROLES_LIST = 'GET_EMPLOYEE_ROLES_LIST';// RECRUITER, SALES, CANDIDATE,


 export const GET_INCENTIVE_TRANSACTIONS_LIST = 'GET_INCENTIVES_TRANSACTION_LIST';
 export const CREATE_NEW_INCENTIVE_TRANSACTION = 'CREATE_NEW_INCENTIVE_TRANSACTION';
 export const UPDATE_INCENTIVE_TRANSACTION = 'UPDATE_INCENTIVE_TRANSACTION';

 export const GET_INCENTIVE_TRANSACTIONS_LIST_SUCCESS_RESPONSE = 'GET_INCENTIVES_TRANSACTION_LIST_SUCCESS_RESPONSE';
 export const CREATE_NEW_INCENTIVE_TRANSACTION_SUCCESS_RESPONSE = 'CREATE_NEW_INCENTIVE_TRANSACTION_SUCCESS_RESPONSE';
 export const UPDATE_INCENTIVE_TRANSACTION_SUCCESS_RESPONSE = 'UPDATE_INCENTIVE_TRANSACTION_SUCCESS_RESPONSE';


export const GET_PAYROLL_TYPE_LIST = 'GET_PAYROLL_TYPE_LIST';// W2, c2c, new w2
export const GET_TEAMS_LIST = 'GET_TEAMS_LIST';
export const GET_EMPLOYEES_LIST = 'GET_EMPLOYEES_LIST';
export const GET_SALES_PERSONS_LIST = 'GET_SALES_PERSONS_LIST';
export const GET_RECRUITERS_LIST = 'GET_RECRUITERS_LIST';

export const GET_INITIAL_DATA_LIST = 'GET_INITIAL_DATA_LIST';

export const GET_INCENTIVE_FOR_VISA_TYPE_FROM_BILL_PAY_RATE = 'GET_INCENTIVE_FOR_VISA_TYPE_FROM_BILL_PAY_RATE';
